#+TITLE: ENGY 5050
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
#+LATEX_HEADER_EXTRA: \newcommand\leftidx[3]{{\vphantom{#2}}#1#2#3}
#+OPTIONS: H:4
#+STARTUP: indent nostars

* Neutron-Nucleus Reactions
A neutron striking a nucleus may elicit a number of different reactions.  The types of reactions may be broadly divided into /absorption/ and /scattering/ reactions.  Absorption reactions are those in which the neutron is integrated into the nucleus, forming a new nucleus.  Normally this results in an excited, unstable nucleus.  The most common way for the nucleus to alleviate the pressure of the new nucleon is through emission of a photon.  The neutron never re-emerges, so this type of reaction is called a /capture/ reaction.  For fissile isotopes, the absorption process normally causes the nucleus to split violently into two pieces, or in other words, /fission/.

Scattering-type reactions can be broadly divided into two categories: /elastic/ and /inelastic/.  Elastic scattering may be viewed as a classical collision between two solid, non-deformable objects.  Billiard balls are the prototypical example.  Because neither object is "deformed" or excited, energy and linear momentum are conserved in the system.  This is in contrast to inelastic collisions.  

In inelastic scattering reactions, the neutron is actually temporarily absorbed into the nucleus, bringing the nucleus to a compound, excited state.  The compound nucleus then relaxes by emitting both a neutron /and/ a photon within a small fraction of a second.  The absorption-reemission process is so fast (with respect to all other time scales of neutron transport) that it may safely be regarded as instantaneous.  Because of the photon emission, neither the kinetic energy nor the momentum of the neutron-nucleus system is conserved.

Nuclear interactions are typically labeled by identifying the target nucleus, the incoming projectile/particle, particles emitted after the reaction, and the nucleus remaining when the dust settles.  For example, given a nucleus $A$ that is struck by a particle $p$ leading to the emission of particle $q$ and a new nucleus $B$ one would write $A(p,q)B$.  If the nuclei $A$ and $B$ are implicitly assumed then we may simply identify the reaction as a $(p,q)$ reaction.  Thus our reaction hierarchy so far may be written as

- Absorptions
  - Capture, $(n,\gamma)$
  - Fission, $(n,f)$
- Scattering
  - Elastic scattering, $(n,n)$
  - Inelastic scattering, $(n,n')$

Note that we have abused the original notation somewhat (this is standard) by writing $f$ in place of an ejected particle to denote fission.  We have also written $n'$ as the ejected particle in inelastic scattering as a reminder that the ejected particle will in general /not/ be the same neutron that struck the nucleus.  In some cases, high-energy inelastic scattering reactions may in fact yield more than one neutrons, in which would be denoted $(n,2n)$, $(n,3n)$, etc. with no apostrophe on the ejected particles.

** Scattering Reactions
To describe the kinematics of neutron-nucleus scattering we will begin with several assumptions.
1. Relativistic effects can be neglected.  The kinetic energies of neutrons emitted from fission are low enough so that the space-time effects described by relativity may be neglected.
2. Neutron-neutron interactions will be neglected.  Because the density of nuclei in a reactor is much higher than the density of neutrons, neutrons are much more likely to collide with nuclei than they are with other neutrons.
3. Neutrons travel in straight lines between collisions.  This assumption holds because neutrons are neutrally-charged particles and the effect of gravity on neutron trajectories is negligible.
4. Reactors materials are isotropic.  This means that a material has no preferred orientation.  On the scale of neutron-nucleus interactions in a reactor this is a valid assumption.

*** Scattering Kinematics

Let us now consider the specific kinematics associated with scattering.
- $\vec{V}_n$, $\vec{V}_n'$ :: initial and final velocity of the neutron.
- $E$, $E'$ :: initial and final kinetic energy of the neutron.
- $\vec{V}_A$, $\vec{V}_A'$ :: initial and final velocity of the nucleus.
We also define the angles $\gamma$, $\theta$, and $\psi$ as shown in the figure.

\begin{figure}
\centering
\begin{tikzpicture}[x=0.25in,y=0.25in,scale=0.75]
  \draw (3,0) circle [radius=1];
  \draw (3,0) node {\large n};
  \draw [->,thick] (4.5,0) -- (9.5,0);
  \draw (7.25,1) node {$\vec{V}_n$};

  \draw (15,-5) circle [radius=2];
  \draw (15,-5) node {\huge A};
  \draw [->,thick] (13,-3) -- (10.5,-0.5);
  \draw (11,-2) node {$\vec{V}_A$};

  \draw[dashed] (10,0) -- (18,0);

  \draw (12,0) arc [start angle=0, end angle=-45, radius=2];
  \draw (12.3,-1) node {$\gamma$};

  \draw (15.77,-12.11) circle [radius=1];
  \draw (15.77,-12.11) node {\large n};
  \draw [<-,thick] (14.5,-12.75) -- (10,-15);
  \draw (11.75,-13) node {$\vec{V}_n$};

  \draw (14.87,-18.25) circle [radius=2];
  \draw (14.87,-18.25) node {\huge A};
  \draw [<-,thick] (13,-17) -- (10,-15);
  \draw (11,-16.5) node {$\vec{V}_A$};

  \draw[dashed] (2,-15) -- (18,-15);

  \draw (12,-15) arc [start angle=0, end angle=-33.69, radius=2];
  \draw (12.34,-15.7) node {$\psi$};

  \draw (11.5,-15) arc [start angle=0, end angle=26.57, radius=1.5];
  \draw (12.3,-14.4) node {$\theta$};
\end{tikzpicture}
\caption{Neutron-nucleus collision in LAB coordinates.}
\end{figure}

The analysis of scattering kinematics is greatly simplifed by working in the center-of-mass reference frame (CM) rather than the laboratory reference frame (LAB).  The origin in the CM reference frame is 
\begin{align*}
  \vec{r}_{CM} = \frac{1}{A+1} \left( \vec{r}_n + A\vec{r}_A \right)
\end{align*}
where $\vec{r}_n$ and $\vec{r}_A$ are the positions of the neutron and the nucleus, respectively, and $A$ is the atomic mass ratio of the nucleus.  Consequently we may deduce that the origin of the CM system is moving with a velocity of
\begin{align*}
  \vec{V}_{CM} = \frac{1}{A+1} \left(\vec{V}_n + A\vec{V}_A \right).
\end{align*}

The velocities of the neutron and nuclear in the CM system are given by the following relations:
\begin{subequations}
\begin{align*}
  \vec{v}_n  &= \vec{V}_n - \vec{V}_{CM} \\
  \vec{v}_n' &= \vec{V}_n' - \vec{V}_{CM} \\ 
  \vec{v}_A  &= \vec{V}_A - \vec{V}_{CM} \\
  \vec{v}_A' &= \vec{V}_A' - \vec{V}_{CM}
\end{align*}
\label{eq:cmDefs}
\end{subequations}
We will also define the /relative/ velocity between the neutron and nucleus, which is the same in both the CM and LAB systems:
\begin{align*}
  \vec{V}_R = \vec{V}_n - \vec{V}_A
\end{align*}
This definition allows us to write the CM neutron and nucleus velocities as
\begin{subequations}
\begin{align}
  \vec{v}_n = \frac{A}{A+1}\vec{V}_R \\
  \vec{v}_A = \frac{-1}{A+1}\vec{V}_R
\end{align}
\label{eq:cmVelRel}
\end{subequations}
Thus in the CM system, both neutron and nucleus are moving along the same line in opposite directions before the collision.

Consider now the kinetic energy of the system before the collision.  Letting the variable, $e$, denote the kinetic energy of a particle in the CM system (i.e., relative to the CM velocity) we  have
\begin{align*}
  e_n + e_A = e_{\text{exc}}
\end{align*}
where the subscripts are used in the same way as they were in the velocity variables.  The new variable $e_{\text{exc}}$ is called the /excitation energy/, which is the energy that is available for the reaction, and may be written
\begin{align*}
  e_{\text{exc}} = \frac{1}{2} \frac{mA}{A+1}V_R^2.
\end{align*}

*** Elastic Scattering

We will now assume that linear momentum is conserved through the collision.  In the LAB system this means
\begin{align*}
  \vec{V}_n + A\vec{V}_A = \vec{V}_n' + A\vec{V}_A'
\end{align*}
By using the definitions in Eq. \eqref{eq:cmDefs} we see that this relationship carries over to CM system, allowing us to write
\begin{align*}
  \vec{v}_n + A\vec{v}_A = \vec{v}_n' + A\vec{v}_A'
\end{align*}
Writing the left-hand-side of this expression (i.e., the pre-collision linear momentum) in terms of the relative velocity reveals that net linear momentum both before and after the collision is zero:
\begin{align*}
  \frac{A}{A+1}\vec{V}_R - \frac{A}{A+1}\vec{V}_R = \vec{0}
\end{align*}
This means that
\begin{align*}
  \vec{v}_n = -A \vec{v}_A, \\
  \vec{V}_n' = -A \vec{v}_A'.
\end{align*}

\begin{figure}
\centering
\begin{tikzpicture}[x=0.25in,y=0.25in,scale=0.75]
  \draw (3,0) circle [radius=1];
  \draw (3,0) node {\large n};
  \draw [->,thick] (4.5,0) -- (9.5,0);
  \draw (7.25,1) node {$\vec{v}_n$};

  \draw (15.5,0) circle [radius=2];
  \draw (15.5,0) node {\huge A};
  \draw [->,thick] (13,0) -- (10.5,0);
  \draw (12,1) node {$\vec{v}_A$};


  \draw (15.77,-10.11) circle [radius=1];
  \draw (15.77,-10.11) node {\large n};
  \draw [<-,thick] (14.5,-10.75) -- (10,-13);
  \draw (11.75,-11) node {$\vec{v}_n'$};

  \draw (5.3,-15.35) circle [radius=2];
  \draw (5.3,-15.35) node {\huge A};
  \draw [<-,thick] (7.3,-14.34) -- (10,-13);
  \draw (9.8,-14.2) node {$\vec{v}_A'$};

  \draw[dashed] (2,-13) -- (18,-13);

  \draw (11.5,-13) arc [start angle=0, end angle=26.57, radius=1.5];
  \draw (12.3,-12.4) node {$\theta$};
\end{tikzpicture}
\caption{Neutron-nucleus collision in CM coordinates.}
\end{figure}

Let us now additionally assume conservation of kinetic energy before and after the collision.  That is, 
\begin{align*}
  e_n + e_A = e_n' + e_A' = e_{\text{exc}}.
\end{align*}
Using Eq. \eqref{ref:eq:cmVelRel}, we find that 
\begin{align*}
  v_n = v_n' = \frac{A}{A+1}V_R,
\end{align*}
and
\begin{align*}
  v_A = v_A' = \frac{1}{A+1}V_R.
\end{align*}

**** Stationary Target Nucleus
Consider the special case where target nucleus is stationary, i.e. $\vec{V}_A = 0$.  From the previous section we know that
\begin{align*}
  \vec{V}_{CM} = \frac{1}{A+1} \vec{V}_n, \text{ and} \\
  v_n = v_n' = \frac{A}{A+1}V_n.
\end{align*}
We can sketch a diagram of the relationship between the LAB and CM velocities and the velocity of the center-of-mass.

\begin{figure}
\centering
\begin{tikzpicture}[x=0.25in,y=0.25in,scale=0.75]
  \draw [->,thick] (0,0) -- (13,0);
  \draw (6.5,0) node[anchor=north] {$\vec{V}_{CM}$};

  \draw [->,thick] (0,0) -- (20,8);
  \draw (10,4) node[anchor=south east] {$\vec{V}_n'$};

  \draw [->,thick] (13,0) -- (19.65,7.6);
  \draw (16.5,4) node[anchor=north west] {$\vec{v}_n'$};

  \draw [dashed] (13,0) -- (21,0);

  \draw (15,0) arc [start angle=0, end angle=48.84, radius=2];
  \draw (15.5,1) node {$\varphi$};

  \draw (4,0) arc [start angle=0, end angle=21.8, radius=4];
  \draw (4.5,1) node {$\theta$};
\end{tikzpicture}
\caption{Relationship between final neutron velocities in LAB and CM.}
\end{figure}

From this diagram, we can apply the law of cosines to find
\begin{equation}
  V_n'^2 = V_{CM}^2 + v_n'^2 + 2 V_{CM}v_n'\cos(\pi-\varphi)
\end{equation}
which simplifies to
\begin{equation}
  V_n'^2 = \left[ \frac{A^2+1}{(A+1)^2} + 2 \frac{A}{(A+1)^2}\cos(\varphi) \right] \vec{V}_n^2.
\end{equation}
An immediate implication of this expression is the relationship between the final and initial kinetic energies of the neutron and the scattering angle in the CM system:
\begin{align*}
  \frac{E_n'}{E_n} = \frac{V_n'^2}{\vec{V}_n^2}
                   = \frac{(1+\alpha) + (1-\alpha) \cos(\varphi)}{(A+1)^2}
\end{align*}
where
\begin{align*}
  \alpha = \left( \frac{A-1}{A+1} \right)^2
\end{align*}

To understand this a bit better let's consider a few limiting cases.
- $A=1$ :: This is the case of a neutron scattering off a hydrogen nucleus, and $\alpha = 0$.  For a glancing collision, the angle of deflect ($\varphi$ or $\theta$) will be very small.  Thus $E_n' \approx E_n$ and no appreciable energy is lost in the collision.  For a direct hit, in which case the neutron bounces straight back ($\varphi = \theta = \pi$) we have $E_n' = 0$--the neutron lost /all/ of its energy in a single collision.
- $A>>1$ :: In this case the neutron hits something big, and $\alpha \approx 1$.  Under these circumstances $E_n' \approx E_n$ /regardless/ of the deflection angle.  Think of throwing a tennis ball against a brick wall.

Another important ramification is that for any fixed size of the target nucleus, $A$, their is a limited range of possible final energies for the neutron.  The largest energy loss will occur when the neutron is scattered directly backward, in which case $E_n' = \alpha E_n$.  On the other hand, for a small-angle glancing collision, the final energy will be only slightly less than the initial energy and $E_n' \approx E_n$.  Note that under our current assumptions (namely, that the target nucleus is stationary) the neutron will never /gain/ energy.

The preceding work shows us that the amount of energy lost by a neutron depends on the mass of the target nucleus and the cosine of the deflection angle in the CM system.  We can derive a similar relationship between the energy loss and the cosine of the deflection angle in the LAB system, which is often more useful from simulation perspective.

Again starting with the diagram and using the law of cosines we have
\begin{align*}
  v_n'^2 = V_n'^2 + V_{CM}^2 - 2 V_n' V_{CM} \cos\theta.
\end{align*}
This simplifies to 
\begin{align*}
  \left( \frac{A}{A+1} \right)^2 V_n^2 = V_n'^2 + \left( \frac{1}{A+1} \right)^2 V_n^2 - \frac{2}{A+1} V_n' V_n \cos\theta.
\end{align*}
Multiplying by the mass of a neutron squared divided by four (to get an expression in terms of energies) and solving for $\cos\theta$ yields
\begin{align*}
  \cos\theta = \frac{1}{2}\left( A+1 \right) \sqrt{\frac{E_n'}{E_n}}
             - \frac{1}{2}\left( A-1 \right) \sqrt{\frac{E_n}{E_n'}}.
\end{align*}

*** Reactions Involving a Compound Nucleus
Elastic scattering may be viewed a billiard ball collision.  The neutron and nucleus exchange kinetic energy and linear momentum but nothing else.  In collisions such as inelastic scattering, neutron capture, and fission however, the neutron and nucleus combine to form a new, compound nucleus.  Moreover, this compound nucleus will generally be in an /excited/ state, having received additional internal energy from the collision.  We may write such a reaction as
\begin{align*}
  \leftidx{^A_Z}{X}{} + \leftidx{^1_0}{n}{} 
  \rightarrow \leftidx{^{A+1}_Z}{X}{^*}
\end{align*}
where the * symbol is used to indicate an excited state.  The first reaction in this process is the absorption of a neutron into the target nucleus.  The resultant excited nucleus will then decay, generally on a time scale of $10^{-14}$ to $10^{-21}$ seconds.

There are two sources of the excitation energy in a compound nucleus.  First, there is the kinetic energy that is available to the reaction.  This energy, $e_{\text{exc}}$, is the total pre-collision kinetic energy of the neutron and nucleus in the CM reference frame.  Second, there is a potential source of energy arising from the change in binding energy between the original and compound nuclei.  This change in energy may be expressed as
\begin{align*}
  \Delta BE = \left[ M(A,z) + m_n - M(A+1,Z) \right] c^2
\end{align*}
where $M(A,Z)$ is the mass of nucleus $\leftidx{^A_Z}{X}{}$, $m_n$ is the mass of the neutron and $c$ is the speed of light in a vacuum.  Thus the total energy available to the reaction is $e_{\text{exc}} + \Delta BE$.

Because of the quantum nature of reality, which is very important at the nuclear scale, a nucleus is not allowed to be excited to an arbitrary energy level.  Rather a nucleus may only sit at certain discrete energy levels, at or above its ground state.  Nuclei in excited states will seek to return to the stable ground state through some combination of photon and/or neutron emission.  For some nuclei, the additional energy is sufficient to cause fission.  A discussion of the quantum effects surrounding nucleus formation and de-excitation can quickly become quite involved.  While interesting, that discussion is beyond the objectives of our present endeavor.  Thus the following brief sections will only present a high-level summary of the things it might be good to know as nuclear /engineer/.

**** Inelastic Scattering
Inelastic scattering involves the formation of a compound nucleus which subsequently decays through the emission of a neutron and one or more photons (\gamma rays):
\begin{align*}
  \leftidx{^A_Z}{X}{} + \leftidx{^1_0}{n}{} 
  \rightarrow \leftidx{^{A+1}_Z}{X}{^*}
  \rightarrow \leftidx{^A_Z}{X}{} + \leftidx{^1_0}{n}{} + \gamma
\end{align*}
The presence of the photon at the end of this reaction clearly indicates that energy has not been conserved between the neutron-nucleus pair.  What has happened instead, is that upon ejection of the neutron, the $\leftidx{^A_Z}{X}{}$ was actually left in an excited state and emitted one (or more) photons to return to the ground state.

When considering the energetics of inelastic scattering, note that the final nucleus is simply the original target nucleus.  Thus the role of the change in binding energy has no net effect on the energy of the system.  There was $e_\text{exc}$ energy available before the collision (from the kinetic energy of the neutron and nucleus) and there is still $e_\text{exc}$ energy available after the collision, although the photon has appeared and claimed part of the available energy.

A second consideration is that for the compound nucleus to decay into an excited state, there must have been at least enough energy, $e_\text{exc}$, to bridge the gap between the ground and the first excited state.  Otherwise there would not have been enough energy available after the neutron emission for the target nucleus to be in an excited state!  This type of reaction is known as a /threshold/ reaction, because the energy of the colliding pair must meet a certain "threshold" value before the reaction can take place.  Note that if the compound nucleus emits a neutron and returns the target nucleus to its ground state, then there is no photon emission (which is only a result of de-excitation), thus the total energy of the reaction $e_\text{exc}$ is shared between the neutron and nucleus as kinetic energy.  This, however, implies overall conservation of kinetic energy between the neutron and nucleus, thus it is an /elastic/ scattering event!

**** Radiative Capture
A radiative capture reaction is essentially an inelastic neutron scattering /without the neutron/.  That is, the target nucleus absorbs a neutron then de-excites simply by emitting one or more photons:
\begin{align*}
  \leftidx{^A_Z}{X}{} + \leftidx{^1_0}{n}{} 
  \rightarrow \leftidx{^{A+1}_Z}{X}{^*} + \gamma
\end{align*}
Note that the total amount of energy to be relieved through the emission of photons is $e_{\text{exc}} + \Delta BE$.

**** Fission Reactions
In a fission reaction, the energy $e_{\text{exc}} + \Delta BE$ is enough to overcome the fission barrier (which is an energy threshold), and the nucleus splits into two fragments plus several free neutrons and photons.  The nuclear configuration of the fission fragments and the number of free neutrons emitted are both statistical quantities.  
** Problems
1. Show that conservation of linear momentum in the LAB system implies conservation of linear momentum in the CM system.
2. Show that conservation of energy in the LAB system implies conservation of energy in the CM system.

** References
- [[ebib:Hebert2009][Hebert]]
- [[ebib:Duderstadt:Hamilton1976][Duderstadt and Hamilton]]
- [[ebib:Stacey2001][Stacey]]
* Cross Sections
We have already assumed that neutrons travel along straight trajectories between collisions and argued that this is indeed a valid assumption within studies of nuclear reactor physics.  But how can we characterize the frequency of collisions for neutrons traveling along a given trajectory?  Put another way, if a neutron start along a trajectory from a known point, how long should we expect it to travel before it experiences a collision.  This is clearly a problem for probability.  Hebert (2009) summarizes the problem nicely.

#+BEGIN_QUOTE
The probablity for a neutron located at $\vec{r}$ and moving in a material at velocity $\vec{V}_n$ to undergo a nuclear reaction in a differential element of trajectory $ds$ is independent of the past history of the neutron and is proportional to $ds$.
#+END_QUOTE

In concrete terms, let's say that we have a  neutron that starts moving at a fixed velocity a medium  containing a exactly one kind of nucleus.  Then define $P[ds]$ as the probability that the neutron will experience a collision within a differential distance $ds$, and consider the following
- We were told (above) that the probability $P[ds]$ is proportional to $ds$.
- From intuition, we can also convince ourselves that this probability should also be proportional to the number of "target" nuclei present, so let's define $N$ as the density of nuclei.
From these observations we may write
\begin{align*}
  P[ds] = \sigma N ds
\end{align*}
The quantity $P[ds]$ is a probability, so it should be unitless.  Given that $N$ is a density and $ds$ is length, we can infer that the proportionality constant, $\sigma$, has units of length squared or area.  The constant $\sigma$ is called the /microscopic cross section/.  It is common to express the microscopic cross section in units of /barns/ (b) where $1 \text{ b} = 10^{-24} \text{ cm}^2$.

The product of the first two variables appearing on the right-hand-side of the probability definition is called the /macroscopic cross section/, written as
\begin{align*}
  \Sigma = \sigma N,
\end{align*}
which may be interpreted as the probability /per unit path-length/ of a collision.  Thus we may write the probability of a neutron collision over the differential path-length $ds$ as
\begin{align*}
  P[ds] = \Sigma ds.
\end{align*}

Next, consider a /population/ of neutrons with a density, $n$.  For now let's assume that all neutrons have the same speed, but they need not be moving in the same direction.  The number of neutrons that will experience a collision within the differential path-length $ds$ along each of their individual trajectories will be $P[ds]$ multiplied by the number of neutrons.  If we multiply by the /density/ of neutrons rather than the /number/ of neutrons then we get the (differential) density of neutron collisions within a (differential) distance $ds$ of collective neutron travel:
\begin{align*}
  dC = \Sigma n ds.
\end{align*}
Note the units of (collisions) per unit volume.

Because all neutrons are moving at the same speed, $V_n$, we may relate the distance $ds$ (of "collective neutron travel") to a time interval $dt = \frac{ds}{V_n}$.  Thus the density of neutron collisions is $dC = \Sigma n V_n dt$.  Dividing by $dt$ and taking $dt \rightarrow 0$ gives us an important quantity in reactor physics, called the /reaction rate density/:
\begin{align*}
  R = \frac{dC}{dt} = \Sigma n V_n.
\end{align*}
Because we have officially taken the limit $dt \rightarrow 0$ (and correspondingly $ds \rightarrow 0$), this quantity is a point-wise, instantaneous value.

The product of neutron density and neutron speed, $n V_n$, appearing on the right-hand-side of the reaction rate density is a ubiquitous quantity in reactor physics, called the /scalar flux/:
\begin{align*}
  \phi = n V_n.
\end{align*}

We have previously established that there are several different types of nuclear reactions (radiative capture, elastic and inelastic scattering, etc.)  Each type of reaction is represented by unique microscopic cross section.  For a reaction of type $x$, for example, we may write the corresponding cross section $\sigma_x$.  Multiplying by the nuclide density provides the corresponding macroscopic cross section $\Sigma_x = N \sigma_x$.

If there is more than one type of nuclide present, we may simply add the contributions from each to obtain macroscopic cross section for the mixture:
\begin{align*}
  \Sigma_x = \sum_i N_i \sigma_{x,i}.
\end{align*}
More over we may sum across all reaction types to obtain the /total/ macroscopic cross sections, which is the probability per unit path-length of /any/ collision:
\begin{align*}
  \Sigma = \sum_x \Sigma_x.
\end{align*}

Now consider a monoenergetic beam of neutrons with uniform velocity $\vec{V}_n$ impinging normally on the surface of slab with a total macroscopic cross section $\Sigma$.  On average, how far will a neutron travel into the slab before experiencing its first collision?

First construct a balance equation for the uncollided neutron density as a function of $x$.  We know that the rate of neutron removal (with respect to $x$) will be the rate of neutron collisions, and there are no sources of uncollided neutrons inside the slab.  Thus,
\begin{align*}
  \frac{dn}{dx} = -\Sigma n(x).
\end{align*}
We can solve this equation to determine
\begin{align*}
  n(x) = n(0) e^{-\Sigma x}.
\end{align*}
The probability that a neutron will reach a distance $x$ without experiencing is a collision is thus
\begin{align*}
  p_0(x) = \frac{n(x)}{n(0)} = e^{-\Sigma x}.
\end{align*}

Next, the probability of a neutron experiencing its first collision between $x$ and $x+dx$ is the product of (1) the probability of the neutron reaching $x$ and (2) the probability of the neutron colliding between $x$ and $x+dx$:
\begin{align*}
  p_c(x)dx = p_0(x) \Sigma dx = \Sigma e^{-\Sigma x} dx.
\end{align*}

Finally, the average distance to first collision, which we will call $\lambda$, may be obtained by taking the integral
\begin{align*}
  \lambda = \int_0^\infty x p_c(x) dx = \frac{1}{\Sigma}.
\end{align*}
The quantity $\lambda$ is called the /mean-free-path/ and, for an infinite, homogeneous medium, is equal to the inverse of the total macroscopic cross section.


** References
- [[ebib:Hebert2009][Hebert (2009)]]
